# Generated by Django 2.2.7 on 2019-11-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ima',
            field=models.ImageField(default='', upload_to='hinh/'),
        ),
    ]
