# Generated by Django 2.2.7 on 2019-12-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_image_ima'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='hinh/', verbose_name='data image')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('desciption', models.TextField(blank=True, max_length=500)),
                ('imageGalery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DataForGalery')),
            ],
        ),
    ]
